### PR TITLE
Add support for PHP 8.3

### PR DESCRIPTION
**Pull request by bfolliot**

### CODE REVIEW

**Comment by gsteel** [comment]
Thanks for the patch @bfolliot - #30 needs a review and merging to get CI green. If that one goes in first, you'll likely need to do a rebase as the lock has changed in #30 too.

**Comment by bfolliot** [comment]
@gsteel 
It's done.

**Comment by bfolliot** [comment]
Wouldn't it be better to go straight to `^8.1`?

**Comment by Ocramius** [comment]
@bfolliot PHP does not / cannot follow SemVer.

A full explanation can be found here:  https://github.com/laminas/laminas-diactoros/issues/117#issuecomment-1267306142

**Review by Ocramius — APPROVED** [review]
:ship: thanks @bfolliot!

**Comment by bfolliot** [comment]
Thanks for the explanation @Ocramius

**Pull request merged**
