### PR TITLE
Drop not required code to get or create environment

### PR DESCRIPTION
**Pull request by alexander-schranz**
Signed-off-by: Alexander Schranz <alexander@sulu.io>

|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | no
| RFC           | yes
| QA            | no

### Description

See https://github.com/mezzio/mezzio-platesrenderer/pull/19#discussion_r975246020

### CODE REVIEW

**Review by Ocramius — CHANGES_REQUESTED** [review]
Some tests to be adjusted, check also CI comments :+1:

**Comment by alexander-schranz** [comment]
@Ocramius think the test is not longer required in this case.

**Review by Ocramius — APPROVED** [review]
LGTM 👍

**Comment by Ocramius** [comment]
Ah, one CS issue left

**Comment by Ocramius** [comment]
Thanks @alexander-schranz!

**Pull request merged**
